### ISSUE TITLE
improve performance on scss find usages

### ISSUE THREAD

**Issue by gencer** [gencer/HTML-Slim-CSS-SCSS-Class-Completion#17]
Primary reason for slow performance is that we also cache usages in SCSS files. If we exclude them it is instant.

_I will try to provide an option for this._

**Option provided.** Related option is `enableScssFindUsage`. Find more info in README.md

**Comment by Kcko** [comment]
How it works? How to set it?
I would like the same behavior as with css / php / latte files ...
1) fullscan when we open project at first (initial)
2) adding new classes / identificators to cache from file which i am.

Does it work like this?

**Comment by gencer** [comment]
Let me explain;

The features you want is implemented. One of them is find usages in SCSS files. From SCSS to another SCSS. This makes IntelliSense slow. So, In new version I disabled this feature.

It is on marketplace. Now, If you say i can live with slow intellisense, just open settings.json and this:

```
  "html-css-class-completion.enableScssFindUsage": true,
```

This will enable finsing usages in SCSS files but it will be a little slow. This is what you requested from me on other issue.

**Comment by gencer** [comment]
This issue shopuld stay open because I just hacked by setting. We need more performance.

**Comment by Kcko** [comment]
Thx for explanation:

Let me give you a few questions:

1) When a set directive ```html-css-class-completion.enableScssFindUsage``` to ```false``` i never see path of occurenses.  
![](http://bit.ly/2UWtkIF)

2) When a set directive ```html-css-class-completion.enableScssFindUsage``` to ```true`` i  see path of occurenses.  
![](http://bit.ly/2V11XNN)

If is correct behavior (1+2), so i dont understand misleading naming of this option.

**Comment by gencer** [comment]
Exactly. If you enable enableScssFindUsage this means you will get paths. If you disable (false) you only get paths for php, latte or html... Not scss.

**Comment by Kcko** [comment]
thanks for clarification. 
But I'm afraid it does not work in css files.

With options: ```"html-css-class-completion.enableScssFindUsage": true```
Video:  http://bit.ly/2UQYIbq

With options: ```"html-css-class-completion.enableScssFindUsage": false```
occurences  does not work anywhere
Video: http://bit.ly/2UQZHs8

:-(

**Comment by gencer** [comment]
Fixed.

Sent to marketplace too:

Here: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.11

**Comment by Kcko** [comment]
So fast? Where was the problem? In commits i  do not see some change...

**Comment by gencer** [comment]
Yes, thast fast :=)

Here: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/commit/bba2085d6dd785430574bf4daaf47712f635f5f9

Look at the bottom `extension.ts`. You will see changed line there.

**Comment by gencer** [comment]
And even better: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/commit/5d8c4629fdc6c1fe7dee994c3d5e6c402ab99c84

**Comment by Kcko** [comment]
:-)

Sorry still buggy. 
With false works fine (css / latte occurences works, scss not = fine)
With true works not good (scss / latte works, css not = bad, php some classes are founded, some not ...)

**Comment by Kcko** [comment]
tomorrow is also a day, give rest to ur head.

**Comment by Kcko** [comment]
If you want further information or video, let me know (or tomorrow, im tired :D)

**Comment by Kcko** [comment]
## PHP Behavior
Video: http://bit.ly/2RZodW0
if you wanna PHP code (my old class) to analyze, i will send you on private e-mail.

# option: "html-css-class-completion.enableScssFindUsage": true
Css not showing occurences, you can easily simulate yourself, but if you want video, i´will make it.

**Comment by gencer** [comment]
can you send the sample php file to me via gencer [at] nienbo.co.uk.

It seems something is preventing finding usages in your PHP file. Could be REGEX issue.

**Comment by gencer** [comment]
Fixed in v1.5.12.

Try this build: https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/releases/tag/v1.5.12

**Comment by gencer** [comment]
![image](https://user-images.githubusercontent.com/1711576/52700760-c42fc200-2f89-11e9-8efb-a4476a1910eb.png)

**Comment by Kcko** [comment]
@gencer great works!
There is probably only a second point http://bit.ly/2RZAav8

**Comment by gencer** [comment]
Great to hear that!

For SCSS find usage issue; I will try to reproduce and fix this. Thanks for reporting.

**Comment by Kcko** [comment]
Thx for fast reply & fix.

**Comment by Kcko** [comment]
We can close this and open new issue with second point?

**Comment by gencer** [comment]
Create a new issue but this will remain open because i still need performance tuning for scss.

**Comment by Kcko** [comment]
Yes, i agree, performance is more important :) totally agree.
